[profile.dev]
debug = "full"
split-debuginfo = "off"
strip = "none"

[profile.release]
debug = "full"
split-debuginfo = "off"
strip = "none"

[profile.unstripped]
debug = "full"
split-debuginfo = "off"
strip = "none"
